title: Dylan Edwards
description: Portfolio and Resume
baseurl: "" # Leave empty for GitHub Pages
url: "https://DylanEdwards02.github.io"

# Navigation links
nav:
  - name: About
    link: /about
#  - name: Experience
#    link: /experience
#  - name: Certifications
#    link: /certifications
#  - name: Projects
#    link: /projects
#  - name: Contact
#    link: /contact
